# Generated by Django 4.1.7 on 2023-04-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("caja", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caja",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Nombre"),
        ),
    ]
